config/routes.rb
Rails.application.routes.draw do
  get 'librarians/liberarian'

  resources :issuances
  resources :categories do
  	resources :books
  end
  resources :books do 
  	resources :issuances
  end
  resources :users do
  	resources :groups
  	resources :issuances
  end
  resources :groups do
  	resources :users
  end
  post 'home/login'
  get 'home/student'
  get 'home/proffessor'
  get 'home/liberarian'
  get 'home/admin'
  get 'librarians/liberarian'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  #match ':controller(/:action(/:id))', :via => :get
  root 'home#index'
end

app/models/issuance.rb
class Issuance < ApplicationRecord
	belongs_to :book
	belongs_to :user, :class_name => 'User', :foreign_key => 'issuer_id'
	belongs_to :user, :class_name => 'User', :foreign_key => 'issued_to_id'
end

app/controllers/issuances_controller.rb
class IssuancesController < ApplicationController
  before_action :set_issuance, only: [:show, :edit, :update, :destroy]

  # GET /issuances
  # GET /issuances.json
  def index
    @issuances = Issuance.all
  end

  # GET /issuances/1
  # GET /issuances/1.json
  def show
  end

  # GET /issuances/new
  def new
    @issuance = Issuance.new
  end

  # GET /issuances/1/edit
  def edit
  end

  # POST /issuances
  # POST /issuances.json
  def create
    @issuance = Issuance.new(issuance_params)

    respond_to do |format|
      if @issuance.save
        format.html { redirect_to @issuance, notice: 'Issuance was successfully created.' }
        format.json { render :show, status: :created, location: @issuance }
      else
        format.html { render :new }
        format.json { render json: @issuance.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /issuances/1
  # PATCH/PUT /issuances/1.json
  def update
    respond_to do |format|
      if @issuance.update(issuance_params)
        format.html { redirect_to @issuance, notice: 'Issuance was successfully updated.' }
        format.json { render :show, status: :ok, location: @issuance }
      else
        format.html { render :edit }
        format.json { render json: @issuance.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /issuances/1
  # DELETE /issuances/1.json
  def destroy
    @issuance.destroy
    respond_to do |format|
      format.html { redirect_to issuances_url, notice: 'Issuance was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_issuance
      @issuance = Issuance.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def issuance_params
      params.require(:issuance).permit(:uuid, :book_id, :issuer_id, :issued_to_id, :issuance_date, :return_date, :remark)
    end
end

app/helpers/issuances_helper.rb
module IssuancesHelper
end

app/views/issuances/_form.html.erb
<%= form_for(issuance) do |f| %>
  <% if issuance.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(issuance.errors.count, "error") %> prohibited this issuance from being saved:</h2>

      <ul>
      <% issuance.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :uuid %>
    <%= f.text_field :uuid %>
  </div>

  <div class="field">
    <%= f.label :book_id %>
    <%= f.number_field :book_id %>
  </div>

  <div class="field">
    <%= f.label :issuer_id %>
    <%= f.number_field :issuer_id %>
  </div>

  <div class="field">
    <%= f.label :issued_to_id %>
    <%= f.number_field :issued_to_id %>
  </div>

  <div class="field">
    <%= f.label :issuance_date %>
    <%= f.datetime_select :issuance_date %>
  </div>

  <div class="field">
    <%= f.label :return_date %>
    <%= f.datetime_select :return_date %>
  </div>

  <div class="field">
    <%= f.label :remark %>
    <%= f.text_area :remark %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/issuances/edit.html.erb
<h1>Editing Issuance</h1>

<%= render 'form', issuance: @issuance %>

<%= link_to 'Show', @issuance %> |
<%= link_to 'Back', issuances_path %>

app/views/issuances/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Issuances</h1>

<table>
  <thead>
    <tr>
      <th>Uuid</th>
      <th>Book</th>
      <th>Issuer</th>
      <th>Issued to</th>
      <th>Issuance date</th>
      <th>Return date</th>
      <th>Remark</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @issuances.each do |issuance| %>
      <tr>
        <td><%= issuance.uuid %></td>
        <td><%= issuance.book_id %></td>
        <td><%= issuance.issuer_id %></td>
        <td><%= issuance.issued_to_id %></td>
        <td><%= issuance.issuance_date %></td>
        <td><%= issuance.return_date %></td>
        <td><%= issuance.remark %></td>
        <td><%= link_to 'Show', issuance %></td>
        <td><%= link_to 'Edit', edit_issuance_path(issuance) %></td>
        <td><%= link_to 'Destroy', issuance, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Issuance', new_issuance_path %>

app/views/issuances/new.html.erb
<h1>New Issuance</h1>

<%= render 'form', issuance: @issuance %>

<%= link_to 'Back', issuances_path %>

app/views/issuances/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Uuid:</strong>
  <%= @issuance.uuid %>
</p>

<p>
  <strong>Book:</strong>
  <%= @issuance.book_id %>
</p>

<p>
  <strong>Issuer:</strong>
  <%= @issuance.issuer_id %>
</p>

<p>
  <strong>Issued to:</strong>
  <%= @issuance.issued_to_id %>
</p>

<p>
  <strong>Issuance date:</strong>
  <%= @issuance.issuance_date %>
</p>

<p>
  <strong>Return date:</strong>
  <%= @issuance.return_date %>
</p>

<p>
  <strong>Remark:</strong>
  <%= @issuance.remark %>
</p>

<%= link_to 'Edit', edit_issuance_path(@issuance) %> |
<%= link_to 'Back', issuances_path %>